name: Backup Portal Loop

on:
  # allow to run workflow manually
  workflow_dispatch: { }

  # Triggers the workflow every day at 1am
  schedule:
    - cron: "0 * * * *"

jobs:
  backup:
    name: "backup ${{ matrix.testnet }}"
    runs-on: ubuntu-latest
    timeout-minutes: 360 # very high; but it can take a while.

    permissions:
      contents: write

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        testnet:
          - portal-loop

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.22"

      - name: Run backup script
        run: bash portal-loop/export.sh

      - name: Run stats script
        run: make -C ${{ matrix.testnet }} stats-legacy

      - name: Run extractor
        run: make -C ${{ matrix.testnet }} extractor-legacy

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update ${{ matrix.testnet }} backup"
